=== smckaysmalley/openShift/cs213/assign07.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- assign07.xsd -->

<xs:schema 
   xmlns:xs="http://w3.org/2001/XMLSchema"
   targetNamespace="http://157.201.194.254/~sms329"
   xmlns="http://157.201.194.254/~sms329"
   elementFormDefualt="qualified">

   <xs:element name="firstname" type="xs:string"/>
   <xs:element name="lastname" type="xs:string"/>
   <xs:element name="phone" type="xs:string"/>
   <xs:element name="street" type="xs:string"/>
   <xs:element name="city" type="xs:string"/>
   <xs:element name="state" type="xs:string"/>
   <xs:element name="rank" type="xs:string"/>
   <xs:element name="meritbadge" type="xs:string"/>

   <xs:attribute name="unitname" type="string"/>
   <xs:attribute name="unitnumber" type="string"/>
   <xs:attribute name="dateearned" type="string"/>
   <xs:attribute name="name" type="string"/>

   <xs:element name="address">
     <xs:complexType>
       <xs:sequence>
         <xs:element ref="street"/>
         <xs:element ref="city"/>
         <xs:element ref="state"/>
       </xs:sequence>
     </xs:complexType>
   </xs:element>

   <xs:element name="scout">
     <xs:complexType>
       <xs:sequence>
         <xs:element ref="firstname"/>
         <xs:element ref="lastname"/>
         <xs:element ref="phone"/>
         <xs:element ref="address"/>
         <xs:element ref="rank">
           <xs:complexType>
             <xs:attribute ref="dateearned" use="required"/>
           </xs:complexType>
         </xs:element>
         <xs:element ref="meritbadge">
           <xs:complexType>
             <xs:attribute ref="dateearned" use="required"/>
           </xs:complexType>
         </xs:element>
       </xs:sequence>
     </xs:complexType>
   </xs:element>

   <xs:element name="council">
     <xs:complexType>
       <xs:sequence>
         <xs:element ref="troop"/>
       </xs:sequence>
       <xs:attribute ref="unitnumber" use="required"/>
     </xs:complexType>
   </xs:element>
   
   <xs:element name="troop">
     <xs:complexType>
       <xs:sequence>
         <xs:element ref="scout"/>
       </xs:sequence>
       <xs:attribute ref="unitname" use="required"/>
       <xs:attribute ref="unitnumber" use="required"/>
     </xs:complexType>
   </xs:element>
   
   <xs:element name="bsa">
     <xs:complexType>
       <xs:sequence>
         <xs:element ref="council"/>
       </xs:sequence>
     </xs:complexType>
   </xs:element>
   
</xs:schema>

=== smckaysmalley/openShift/cs213/assign07_xsd.xml
<?xml version = "1.0" encoding = "utf-8"?>
<!-- assign07_dtd.xml -->

<bsa xmlns="" xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="assign07.xsd">
  <council name="Northern New Jersey Council">
    <troop unitnumber="33" unitname="cheese heads">
      <scout>
        <firstname>McKay</firstname>
        <lastname>Smalley</lastname>
        <phone>908-603-9919</phone>
        <address>
          <street>21 Butler Parkway</street>
          <city>Summit</city>
          <state>NJ</state>
        </address>
        <rank>Eagle</rank>
        <meritbadge dateearned="7/19/2000">camping</meritbadge>
        <meritbadge dateearned="7/19/2000">cycling</meritbadge>
        <meritbadge dateearned="7/19/2000">fishing</meritbadge>
        <meritbadge dateearned="7/19/2000">fingerprinting</meritbadge>
        <meritbadge dateearned="7/19/2000">first aid</meritbadge>
        <meritbadge dateearned="7/19/2000">swimming</meritbadge>
        <meritbadge dateearned="7/19/2000">climbing</meritbadge>
      </scout>
      <scout>
        <firstname>Bob</firstname>
        <lastname>Lazar</lastname>
        <phone>908-603-1234</phone>
        <address>
          <street>123 Fake St.</street>
          <city>Summit</city>
          <state>NJ</state>
        </address>
        <rank>Life</rank>
        <meritbadge dateearned="7/19/2000">archery</meritbadge>
        <meritbadge dateearned="7/19/2000">art</meritbadge>
        <meritbadge dateearned="7/19/2000">bugling</meritbadge>
        <meritbadge dateearned="7/19/2000">aviation</meritbadge>
        <meritbadge dateearned="7/19/2000">archaeology</meritbadge>
        <meritbadge dateearned="7/19/2000">astronomy</meritbadge>
        <meritbadge dateearned="7/19/2000">climbing</meritbadge>
      </scout>
      <scout>
        <firstname>Where's</firstname>
        <lastname>Waldo</lastname>
        <phone>908-456-9919</phone>
        <address>
          <street>2 Canoe Brook Parkway</street>
          <city>Summit</city>
          <state>NJ</state>
        </address>
        <rank>Star</rank>
        <meritbadge dateearned="7/19/2000">camping</meritbadge>
        <meritbadge dateearned="7/19/2000">cycling</meritbadge>
        <meritbadge dateearned="7/19/2000">metalwork</meritbadge>
        <meritbadge dateearned="7/19/2000">fingerprinting</meritbadge>
        <meritbadge dateearned="7/19/2000">sports</meritbadge>
        <meritbadge dateearned="7/19/2000">swimming</meritbadge>
        <meritbadge dateearned="7/19/2000">athletics</meritbadge>
      </scout>
      <scout>
        <firstname>Chuck</firstname>
        <lastname>Norris</lastname>
        <phone>303-603-9919</phone>
        <address>
          <street>21 little wolf Rd.</street>
          <city>New Providence</city>
          <state>NJ</state>
        </address>
        <rank>Eagle</rank>
        <meritbadge dateearned="7/19/2000">chess</meritbadge>
        <meritbadge dateearned="7/19/2000">cooking</meritbadge>
        <meritbadge dateearned="7/19/2000">computers</meritbadge>
        <meritbadge dateearned="7/19/2000">fingerprinting</meritbadge>
        <meritbadge dateearned="7/19/2000">first aid</meritbadge>
        <meritbadge dateearned="7/19/2000">swimming</meritbadge>
        <meritbadge dateearned="7/19/2000">dentistry</meritbadge>
      </scout>
      <scout>
        <firstname>Buzz</firstname>
        <lastname>Lightyear</lastname>
        <phone>123-456-7890</phone>
        <address>
          <street>5359 Autumn Creek Dr.</street>
          <city>Newark</city>
          <state>NJ</state>
        </address>
        <rank>Scout</rank>
        <meritbadge dateearned="7/19/2000">geology</meritbadge>
        <meritbadge dateearned="7/19/2000">aviation</meritbadge>
        <meritbadge dateearned="7/19/2000">basketry</meritbadge>
        <meritbadge dateearned="7/19/2000">home repairs</meritbadge>
        <meritbadge dateearned="7/19/2000">first aid</meritbadge>
        <meritbadge dateearned="7/19/2000">robotics</meritbadge>
        <meritbadge dateearned="7/19/2000">Space Exploration</meritbadge>
      </scout>
    </troop>
  </council>
  <council name="The NBA">
    <troop unitnumber="50" unitname="Greatest">
      <scout>
        <firstname>Michael</firstname>
        <lastname>Jordan</lastname>
        <phone>201-603-9919</phone>
        <address>
          <street>23 Main St.</street>
          <city>Chicago</city>
          <state>IL</state>
        </address>
        <rank>Eagle</rank>
        <meritbadge dateearned="7/19/2000">Sports</meritbadge>
        <meritbadge dateearned="7/19/2000">Athletics</meritbadge>
        <meritbadge dateearned="7/19/2000">Aviation</meritbadge>
        <meritbadge dateearned="7/19/2000">Fire Safety</meritbadge>
        <meritbadge dateearned="7/19/2000">first aid</meritbadge>
        <meritbadge dateearned="7/19/2000">swimming</meritbadge>
        <meritbadge dateearned="7/19/2000">climbing</meritbadge>
      </scout>
      <scout>
        <firstname>Lebron</firstname>
        <lastname>James</lastname>
        <phone>908-324-2345</phone>
        <address>
          <street>6 South St.</street>
          <city>Miami</city>
          <state>FL</state>
        </address>
        <rank>Life</rank>
        <meritbadge dateearned="7/19/2000">Sports</meritbadge>
        <meritbadge dateearned="7/19/2000">Athletics</meritbadge>
        <meritbadge dateearned="7/19/2000">fishing</meritbadge>
        <meritbadge dateearned="7/19/2000">wilderness survival</meritbadge>
        <meritbadge dateearned="7/19/2000">first aid</meritbadge>
        <meritbadge dateearned="7/19/2000">Gardening</meritbadge>
        <meritbadge dateearned="7/19/2000">climbing</meritbadge>
      </scout>
      <scout>
        <firstname>Kobe</firstname>
        <lastname>Bryant</lastname>
        <phone>323-603-5432</phone>
        <address>
          <street>24 Main St.</street>
            <city>Los Angeles</city>
            <state>CA</state>
        </address>
        <rank>Star</rank>
        <meritbadge dateearned="7/19/2000">Sports</meritbadge>
        <meritbadge dateearned="7/19/2000">Athletics</meritbadge>
        <meritbadge dateearned="7/19/2000">fishing</meritbadge>
        <meritbadge dateearned="7/19/2000">pets</meritbadge>
        <meritbadge dateearned="7/19/2000">first aid</meritbadge>
        <meritbadge dateearned="7/19/2000">Music</meritbadge>
          <meritbadge dateearned="7/19/2000">energy</meritbadge>
      </scout>
      <scout>
        <firstname>John</firstname>
        <lastname>Stockton</lastname>
        <phone>902-786-0987</phone>
        <address>
            <street>12 Assist Way</street>
            <city>Salt Lake City</city>
            <state>UT</state>
        </address>
        <rank>1st Class</rank>
        <meritbadge dateearned="7/19/2000">Sports</meritbadge>
        <meritbadge dateearned="7/19/2000">Athletics</meritbadge>
        <meritbadge dateearned="7/19/2000">fishing</meritbadge>
        <meritbadge dateearned="7/19/2000">Inventing</meritbadge>
        <meritbadge dateearned="7/19/2000">surveying</meritbadge>
        <meritbadge dateearned="7/19/2000">communication</meritbadge>
        <meritbadge dateearned="7/19/2000">electricity</meritbadge>
      </scout>
      <scout>
        <firstname>Karl</firstname>
        <lastname>Malone</lastname>
        <phone>231-435-6543</phone>
        <address>
          <street>32 Powerhouse Dr.</street>
          <city>Salt Lake City</city>
          <state>UT</state>
        </address>
        <rank>Tenderfoot</rank>
        <meritbadge dateearned="7/19/2000">Sports</meritbadge>
        <meritbadge dateearned="7/19/2000">Athletics</meritbadge>
        <meritbadge dateearned="7/19/2000">fishing</meritbadge>
        <meritbadge dateearned="7/19/2000">Geneology</meritbadge>
        <meritbadge dateearned="7/19/2000">weather</meritbadge>
        <meritbadge dateearned="7/19/2000">truck transportation</meritbadge>
        <meritbadge dateearned="7/19/2000">sculpture</meritbadge>
      </scout>
    </troop>
  </council>
</bsa>
